### ISSUE TITLE
boost::nowide::ifstream fails with std::ifstream::ate

### ISSUE THREAD

**Issue by Zireael-N** [artyom-beilis/nowide#1]
This piece of code throws an exception:
```cpp
std::ifstream::pos_type filesize(const char* filename)
{
    boost::nowide::ifstream in(filename, std::ifstream::ate | std::ifstream::binary);
    if (!in)
        throw std::runtime_error("Couldn't open the file.");
    return in.tellg();
}
```
*If I get rid of std::ifstream::ate, it doesn't throw an exception.*

This piece of code works fine:
```cpp
std::ifstream::pos_type filesize(const char* filename)
{
    std::ifstream in(boost::nowide::widen(filename).c_str(), std::ifstream::ate | std::ifstream::binary);
    if (!in)
        throw std::runtime_error("Couldn't open the file.");
    return in.tellg();
}
```

Compiling with MSVC.

**Comment by artyom-beilis** [comment]
I just forgot to implement ate...
 Artyom Beilis -------------- CppCMS - C++ Web Framework:   http://cppcms.com/ CppDB - C++ SQL Connectivity: http://cppcms.com/sql/cppdb/

**Comment by MikaelSmith** [comment]
Did https://github.com/artyom-beilis/nowide/commit/eaff48de2950ffb6de92ed81c277e5b748e719b7 fix this issue? If so it'd be nice to close it.

**Comment by artyom-beilis** [comment]
Yep it is
