### ISSUE TITLE
Please explicitely state licensing terms until merged into Boost 

### ISSUE THREAD

**Issue by fawick** [artyom-beilis/nowide#10]
As far as I am able to understand, the goal is to have this code included by the Boost project, ultimately making the Boost License become applicable for it. The goal of this issue is to provide legal certainty for fetching and using this code in its current form directly from here.

@artyom-beilis  Until the inclusions happens, would you kindly consider adding and explicit a license statement to clarify how you license your work to the public (e.g. by declaring the Boost License relevant and applicable even now or releasing the code in its current form into the public domain).

I saw that a fork of this project already added a LICENSE, but I since this license statement was not given @artyom-beilis I doubt it can be considered binding https://github.com/webmaster128/nowide/commit/19e7a4c83b7013d4cdac3106707fca934fabc13f

**Comment by artyom-beilis** [comment]
Thanks for reminder.
