### ISSUE TITLE
Potential code issue

### ISSUE THREAD

**Issue by JaapAap** [artyom-beilis/nowide#13]
I am just reading over the code in iostream.cpp. I don't consider myself an expert though and would not know how to test this at this point, but thought I would just bring this to your attention...

In the function `size_t read()` I notice that a value of -1 can be returned to indicate an invalid codepoint is encountered. Should `read() ` not rather return an integer to be able to represent this flag?

Furthermore, in the one and only location where `read()` is called, there is no check on its return value but it is plugged into `setg` right away as:

```
            setg(buffer_,buffer_,buffer_+n);
```
To me it seems that an illegal codepoint would cause a huge value to be used for the last entry, which is potentially harmful.

**Comment by artyom-beilis** [comment]
Yes you are right. It should be fixed.

**Comment by JaapAap** [comment]
Thanks for the fast reply! I suppose that the handling should be similar as in the `write()` case?  How could this be tested, the current test only deals with nominal behaviour I believe?

**Comment by artyom-beilis** [comment]
It is virtually impossible to test as it requires user to enter invalid UTF-16 from keyboard...

**Comment by artyom-beilis** [comment]
Fixed in 9b3c367868a1efa7caa953f27af5eaccd7db8b68
