### ISSUE TITLE
Possible crash in putenv

### ISSUE THREAD

**Issue by artyom-beilis** [artyom-beilis/nowide#14]
> In file included from test\test_system.cpp:11:0:
> ..\../boost/nowide/cenv.hpp: In function 'int boost::nowide::putenv(char*)':
> ..\../boost/nowide/cenv.hpp:104:41: warning: comparison between pointer and
> zero character constant [-Wpointer-compare]
>         while(*key_end!='=' && key_end!='\0')

**Comment by lordofhyphens** [comment]
If it's possible to propagate a null pointer to this function, then there should also be a check for it.

The crash here looks like it will stem from the pointer going out on a journey and not coming back until the segfault comes.

**Comment by artyom-beilis** [comment]
Fixed in review branch
