### ISSUE TITLE
key_end!='\0' should be *key_end!='\0'

### ISSUE THREAD

**Issue by kivadiu** [artyom-beilis/nowide#35]
This bug was highlighted in the boost review but is still there on master:
cenv.hpp:104
while(*key_end!='=' && key_end!='\0')
should be
while(*key_end!='=' && *key_end!='\0')

**Comment by kivadiu** [comment]
Fixed here: https://github.com/artyom-beilis/nowide/pull/39

**Comment by artyom-beilis** [comment]
Already fixed in review branch: #14

**Comment by artyom-beilis** [comment]
This library is in process of integration of Boost - it is work in progress. There are many changes in review branch including API breaking.

Current master is not going to be relevant soon.
