### ISSUE TITLE
#include <stdio.h> should be replaced by #include <cstdio>

### ISSUE THREAD

**Issue by kivadiu** [artyom-beilis/nowide#37]
exists already in C++03 (and 98 I guess) so we can safely use it?
include/boost/nowide/cstdio.hpp:12
include/boost/nowide/filebuf.hpp:16
src/iostream.cpp:11

**Comment by artyom-beilis** [comment]
The functions I need are `_wfopen` and so, they are by no means parts of standard C++03. So OS `stdio.h` is the correct header
