### ISSUE TITLE
nowide::cout crashes in multithreaded

### ISSUE THREAD

**Issue by oomek** [artyom-beilis/nowide#41]
When I call nowide::cout from different threads it crashes. std::cout works fine.

**Comment by oomek** [comment]
reviewfixes branch seemed to fix that problem, so closing.

**Comment by artyom-beilis** [comment]
Just FYI there is no thread safety guarantee on neither std::cout/cerr nor on std::nowide::cout/cerr

**Comment by oomek** [comment]
I'm aware of it, but std::cout just produce mangled output. Thanks for fixing it though.
