### ISSUE TITLE
Printing `\n`?

### ISSUE THREAD

**Issue by MikaelSmith** [artyom-beilis/nowide#6]
The `boost::nowide::cout` implementation appears to skip doing conversion of `\n` to `\r\n` on Windows, which I believe is how `std::cout` normally does it (when not a binary stream). This makes it tricker to get correct line endings on Windows.

**Comment by MikaelSmith** [comment]
Nevermind. This may be a peculiarity of running Windows under Docker.

**Comment by MikaelSmith** [comment]
Ok, this does seem to deviate from `std::cout` behavior on Microsoft Nano Server under Docker (see https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/quick_start_windows_10.md for instructions if you're interested in trying that out). It seems to behave correctly in Windows 10 however, so I'm not exactly sure what might need fixing.

**Comment by artyom-beilis** [comment]
Fixed in 9b3c367868a1efa7caa953f27af5eaccd7db8b68
