### ISSUE TITLE
winconsole_ostream should flush in the destructor

### ISSUE THREAD

**Issue by kivadiu** [artyom-beilis/nowide#8]
This simple program do not print anything:
# include "nowide/iostream.hpp"

int main(int, char**) {
  nowide::cout<<"hello world\n";
  return 0;
}

This is solved by adding flush() to the destructor of winconsole_ostream
winconsole_ostream::~winconsole_ostream() {
  flush();
}

**Comment by artyom-beilis** [comment]
Fixed in 9b3c367868a1efa7caa953f27af5eaccd7db8b68
