### ISSUE TITLE
What font should be used on Windows?

### ISSUE THREAD

**Issue by adishavit** [artyom-beilis/nowide#9]
Running `test_iostream.cpp` on Windows 7:

With DejaVu Sana Mono:
![image](https://cloud.githubusercontent.com/assets/1814800/19219480/e4f800ee-8e1c-11e6-9197-2966df17d6dd.png)

With Consolas:
![image](https://cloud.githubusercontent.com/assets/1814800/19219486/0679b546-8e1d-11e6-9634-0cb86202e25d.png)

With Lucida Console:
![image](https://cloud.githubusercontent.com/assets/1814800/19219489/16922cec-8e1d-11e6-8959-6f7922507c1f.png)

None of them print out the proper strings.

**Comment by artyom-beilis** [comment]
It is problematic but frequently there is no font to handle them all on Windows.

Artyom
